#pragma once
#include <allegro.h>
#include <stdio.h>
#include <allegro/font.h>
#include <allegro/graphics.h>
#include "initialize_set.h"
#include "login.h"
#include "param.h"
#include "new_register.h"
#include "after_login.h"
#include "in_game.h"
